from __future__ import annotations

import copy

import streamlit as st

from main_app.infrastructure.cache_store import CacheStore


SESSION_DEFAULTS = {
    "mind_map_tree": None,
    "mind_map_topic": "",
    "mind_map_last_explained_path": "",
    "mind_map_last_explanation": "",
    "mind_map_selected_path": "",
    "mind_map_graph_direction": "TB",
    "mind_map_view_mode": "Full Graph",
    "mind_map_focus_path": "",
    "flashcards_topic": "",
    "flashcards_cards": [],
    "flashcards_index": 0,
    "flashcards_show_answer": False,
    "flashcards_explanations": {},
    "flashcards_last_explained_index": -1,
    "report_selected_format": "briefing_doc",
    "report_last_topic": "",
    "report_last_format_title": "",
    "report_last_content": "",
    "data_table_topic": "",
    "data_table_columns": [],
    "data_table_rows": [],
    "data_table_last_note": "",
    "quiz_topic": "",
    "quiz_questions": [],
    "quiz_index": 0,
    "quiz_selected_answers": {},
    "quiz_submitted": {},
    "quiz_hints": {},
    "quiz_feedback": {},
    "quiz_explanations": {},
    "quiz_selected_saved_id": "",
    "slideshow_topic": "",
    "slideshow_slides": [],
    "slideshow_index": 0,
    "slideshow_outline": [],
    "slideshow_last_constraints": "",
    "slideshow_last_code_mode": "auto",
    "slideshow_representation_mode": "auto",
    "slideshow_last_representation_mode": "auto",
    "slideshow_background_job_id": "",
    "slideshow_background_job_applied_id": "",
    "video_topic": "",
    "video_payload": None,
    "video_audio_bytes": None,
    "video_audio_error": "",
    "video_full_video_bytes": None,
    "video_full_video_error": "",
    "video_last_constraints": "",
    "video_language": "en",
    "video_slow_audio": False,
    "video_template": "standard",
    "video_animation_style": "smooth",
    "video_representation_mode": "auto",
    "video_use_youtube_prompt": False,
    "video_last_representation_mode": "auto",
    "video_playback_language": "en",
    "video_playback_slow_audio": False,
    "video_slideshow_index": 0,
    "video_background_job_id": "",
    "video_background_job_applied_id": "",
    "audio_overview_topic": "",
    "audio_overview_payload": None,
    "audio_overview_audio_bytes": None,
    "audio_overview_audio_error": "",
    "audio_overview_last_constraints": "",
    "audio_overview_use_youtube_prompt": False,
    "audio_overview_background_job_id": "",
    "audio_overview_background_job_applied_id": "",
    "intent_chat_history": [],
    "intent_chat_last_intents": [],
    "intent_chat_requirements_bundle": {},
    "intent_chat_planner_mode": "Local First (No LLM if possible)",
    "agent_dashboard_history": [],
    "agent_dashboard_pending_plan": None,
    "agent_dashboard_planner_mode": "Local First (No LLM if possible)",
    "agent_dashboard_planner_mode_selector": "Local First (No LLM if possible)",
    "agent_dashboard_active_topic": "",
    "agent_dashboard_recent_topics": [],
    "agent_dashboard_session_id": "",
    "agent_dashboard_session_created_at": "",
    "agent_dashboard_selected_saved_session_id": "",
    "agent_dashboard_saved_session_selector": "",
    "agent_dashboard_force_sync_planner_selector": False,
    "agent_dashboard_force_sync_saved_selector": False,
    "agent_dashboard_store_initialized": False,
}


def initialize_session_state(cache_store: CacheStore) -> None:
    if "llm_cache" not in st.session_state:
        st.session_state.llm_cache = cache_store.load()

    for key, default_value in SESSION_DEFAULTS.items():
        if key not in st.session_state:
            st.session_state[key] = copy.deepcopy(default_value)
