from __future__ import annotations

from io import BytesIO
from typing import Any

from main_app.shared.slideshow.representation_normalizer import normalize_slide_representation
from main_app.services.pptx_export.models import PptxTemplateStyle
from main_app.services.pptx_export.text_utils import normalize_text, prepare_code_payload, split_line_for_slide, trim_code_for_slide


class PdfDeckBuilder:
    def __init__(self, *, style: PptxTemplateStyle) -> None:
        self._style = style

    def build(self, *, topic: str, slides: list[dict[str, Any]]) -> tuple[bytes | None, str | None]:
        try:
            from reportlab.pdfgen import canvas  # type: ignore
        except Exception:
            return None, "reportlab is not installed. Install dependencies to enable PDF export."

        page_width = 960.0
        page_height = 540.0
        output = BytesIO()
        pdf = canvas.Canvas(output, pagesize=(page_width, page_height))

        self._add_pdf_title_slide(
            pdf=pdf,
            topic=topic,
            page_width=page_width,
            page_height=page_height,
        )
        for item in slides:
            self._add_pdf_content_slide(
                pdf=pdf,
                item=item if isinstance(item, dict) else {},
                page_width=page_width,
                page_height=page_height,
            )
        pdf.save()
        return output.getvalue(), None

    @staticmethod
    def _set_pdf_fill_color(pdf: Any, color: tuple[int, int, int]) -> None:
        pdf.setFillColorRGB(color[0] / 255.0, color[1] / 255.0, color[2] / 255.0)

    @staticmethod
    def _set_pdf_stroke_color(pdf: Any, color: tuple[int, int, int]) -> None:
        pdf.setStrokeColorRGB(color[0] / 255.0, color[1] / 255.0, color[2] / 255.0)

    def _add_pdf_title_slide(
        self,
        *,
        pdf: Any,
        topic: str,
        page_width: float,
        page_height: float,
    ) -> None:
        self._draw_pdf_background(
            pdf=pdf,
            page_width=page_width,
            page_height=page_height,
        )

        topic_lines = self._wrap_pdf_text(
            pdf=pdf,
            text=normalize_text(topic) or "Slide Deck",
            font_name="Helvetica-Bold",
            font_size=44,
            max_width=page_width - 100.0,
            max_lines=3,
        )
        title_y = page_height - 150.0
        self._set_pdf_fill_color(pdf, self._style.title_color)
        pdf.setFont("Helvetica-Bold", 44)
        for line in topic_lines:
            pdf.drawString(50.0, title_y, line)
            title_y -= 52.0

        subtitle = f"Generated by Knowledge App | Template: {self._style.title}"
        self._set_pdf_fill_color(pdf, self._style.body_color)
        pdf.setFont("Helvetica", 20)
        pdf.drawString(50.0, 110.0, subtitle)
        pdf.showPage()

    def _add_pdf_content_slide(
        self,
        *,
        pdf: Any,
        item: dict[str, Any],
        page_width: float,
        page_height: float,
    ) -> None:
        normalized_item, _ = normalize_slide_representation(item if isinstance(item, dict) else {})
        self._draw_pdf_background(
            pdf=pdf,
            page_width=page_width,
            page_height=page_height,
        )

        section = normalize_text(normalized_item.get("section", ""))
        if section:
            chip_height = 28.0
            chip_width = min(
                240.0,
                max(120.0, pdf.stringWidth(section[:36], "Helvetica-Bold", 12) + 26.0),
            )
            chip_x = page_width - chip_width - 34.0
            chip_y = page_height - 52.0
            self._set_pdf_fill_color(pdf, self._style.section_chip_color)
            self._set_pdf_stroke_color(pdf, self._style.section_chip_color)
            pdf.roundRect(chip_x, chip_y, chip_width, chip_height, 8.0, fill=1, stroke=0)
            self._set_pdf_fill_color(pdf, self._style.section_chip_text_color)
            pdf.setFont("Helvetica-Bold", 12)
            pdf.drawString(chip_x + 12.0, chip_y + 9.0, section[:36])

        title_lines = self._wrap_pdf_text(
            pdf=pdf,
            text=normalize_text(normalized_item.get("title", "Untitled")) or "Untitled",
            font_name="Helvetica-Bold",
            font_size=28,
            max_width=page_width - 80.0,
            max_lines=2,
        )
        self._set_pdf_fill_color(pdf, self._style.title_color)
        pdf.setFont("Helvetica-Bold", 28)
        title_y = page_height - 86.0
        for line in title_lines:
            pdf.drawString(36.0, title_y, line)
            title_y -= 34.0

        raw_code_snippet = str(normalized_item.get("code_snippet", ""))
        raw_code_language = normalize_text(normalized_item.get("code_language", ""))
        code_snippet, code_language = prepare_code_payload(
            code_snippet=raw_code_snippet,
            code_language=raw_code_language,
        )
        bullets = normalized_item.get("bullets", [])
        if not isinstance(bullets, list):
            bullets = []
        bullet_texts = [normalize_text(bullet) for bullet in bullets if normalize_text(bullet)]
        if not bullet_texts:
            bullet_texts = ["Key concept summary for this slide."]
        representation = " ".join(str(normalized_item.get("representation", "bullet")).split()).strip().lower()
        layout_payload = normalized_item.get("layout_payload", {})
        if not isinstance(layout_payload, dict):
            layout_payload = {}

        content_top = page_height - 160.0
        content_bottom = 52.0
        if code_snippet:
            self._draw_pdf_bullets(
                pdf=pdf,
                bullets=bullet_texts[:6],
                x=38.0,
                y_top=content_top,
                width=418.0,
                y_bottom=content_bottom,
                font_size=15,
            )
            self._draw_pdf_code_panel(
                pdf=pdf,
                code_snippet=code_snippet,
                code_language=code_language,
                x=475.0,
                y_top=content_top,
                width=448.0,
                height=content_top - content_bottom,
            )
        else:
            self._draw_pdf_representation(
                pdf=pdf,
                representation=representation,
                layout_payload=layout_payload,
                fallback_bullets=bullet_texts[:6],
                y_top=content_top,
                y_bottom=content_bottom,
            )

        pdf.showPage()

    def _draw_pdf_representation(
        self,
        *,
        pdf: Any,
        representation: str,
        layout_payload: dict[str, Any],
        fallback_bullets: list[str],
        y_top: float,
        y_bottom: float,
    ) -> None:
        if representation == "two_column":
            self._draw_pdf_two_column(
                pdf=pdf,
                left_title=str(layout_payload.get("left_title", "Left")),
                left_items=self._to_string_list(layout_payload.get("left_items")),
                right_title=str(layout_payload.get("right_title", "Right")),
                right_items=self._to_string_list(layout_payload.get("right_items")),
                fallback_bullets=fallback_bullets,
                y_top=y_top,
                y_bottom=y_bottom,
            )
            return
        if representation == "comparison":
            self._draw_pdf_two_column(
                pdf=pdf,
                left_title=str(layout_payload.get("left_title", "Option A")),
                left_items=self._to_string_list(layout_payload.get("left_points")),
                right_title=str(layout_payload.get("right_title", "Option B")),
                right_items=self._to_string_list(layout_payload.get("right_points")),
                fallback_bullets=fallback_bullets,
                y_top=y_top,
                y_bottom=y_bottom,
            )
            return
        if representation == "timeline":
            self._draw_pdf_timeline(
                pdf=pdf,
                events=layout_payload.get("events"),
                fallback_bullets=fallback_bullets,
                y_top=y_top,
                y_bottom=y_bottom,
            )
            return
        if representation == "process_flow":
            self._draw_pdf_process_flow(
                pdf=pdf,
                steps=layout_payload.get("steps"),
                fallback_bullets=fallback_bullets,
                y_top=y_top,
                y_bottom=y_bottom,
            )
            return
        if representation == "metric_cards":
            self._draw_pdf_metric_cards(
                pdf=pdf,
                cards=layout_payload.get("cards"),
                fallback_bullets=fallback_bullets,
                y_top=y_top,
            )
            return
        self._draw_pdf_bullets(
            pdf=pdf,
            bullets=fallback_bullets,
            x=40.0,
            y_top=y_top,
            width=880.0,
            y_bottom=y_bottom,
            font_size=17,
        )

    def _draw_pdf_two_column(
        self,
        *,
        pdf: Any,
        left_title: str,
        left_items: list[str],
        right_title: str,
        right_items: list[str],
        fallback_bullets: list[str],
        y_top: float,
        y_bottom: float,
    ) -> None:
        if not left_items and not right_items:
            midpoint = max(1, len(fallback_bullets) // 2)
            left_items = fallback_bullets[:midpoint]
            right_items = fallback_bullets[midpoint:]
        self._set_pdf_fill_color(pdf, self._style.title_color)
        pdf.setFont("Helvetica-Bold", 15)
        pdf.drawString(42.0, y_top + 6.0, normalize_text(left_title) or "Left")
        pdf.drawString(490.0, y_top + 6.0, normalize_text(right_title) or "Right")
        self._draw_pdf_bullets(
            pdf=pdf,
            bullets=left_items[:4] or ["No content provided."],
            x=40.0,
            y_top=y_top - 20.0,
            width=400.0,
            y_bottom=y_bottom,
            font_size=14,
        )
        self._draw_pdf_bullets(
            pdf=pdf,
            bullets=right_items[:4] or ["No content provided."],
            x=490.0,
            y_top=y_top - 20.0,
            width=430.0,
            y_bottom=y_bottom,
            font_size=14,
        )

    def _draw_pdf_timeline(
        self,
        *,
        pdf: Any,
        events: Any,
        fallback_bullets: list[str],
        y_top: float,
        y_bottom: float,
    ) -> None:
        parsed_events: list[tuple[str, str]] = []
        if isinstance(events, list):
            for event in events[:5]:
                if not isinstance(event, dict):
                    continue
                label = normalize_text(event.get("label", ""))
                detail = normalize_text(event.get("detail", ""))
                if label or detail:
                    parsed_events.append((label, detail))
        if not parsed_events:
            parsed_events = [(f"Milestone {idx + 1}", bullet) for idx, bullet in enumerate(fallback_bullets[:5])]
        if not parsed_events:
            parsed_events = [("Milestone", "No timeline events provided.")]

        y = y_top - 8.0
        for label, detail in parsed_events:
            if y < y_bottom + 24.0:
                break
            self._set_pdf_fill_color(pdf, self._style.accent_color)
            pdf.circle(48.0, y + 4.0, 3.0, fill=1, stroke=0)
            self._set_pdf_fill_color(pdf, self._style.title_color)
            pdf.setFont("Helvetica-Bold", 14)
            pdf.drawString(60.0, y, label or "Milestone")
            if detail:
                self._set_pdf_fill_color(pdf, self._style.body_color)
                pdf.setFont("Helvetica", 12)
                wrapped = self._wrap_pdf_text(
                    pdf=pdf,
                    text=detail,
                    font_name="Helvetica",
                    font_size=12,
                    max_width=840.0,
                    max_lines=2,
                )
                current = y - 14.0
                for line in wrapped:
                    pdf.drawString(60.0, current, line)
                    current -= 14.0
                y = current - 8.0
            else:
                y -= 26.0

    def _draw_pdf_process_flow(
        self,
        *,
        pdf: Any,
        steps: Any,
        fallback_bullets: list[str],
        y_top: float,
        y_bottom: float,
    ) -> None:
        parsed_steps: list[tuple[str, str]] = []
        if isinstance(steps, list):
            for step in steps[:5]:
                if not isinstance(step, dict):
                    continue
                title = normalize_text(step.get("title", ""))
                detail = normalize_text(step.get("detail", ""))
                if title or detail:
                    parsed_steps.append((title or "Step", detail))
        if not parsed_steps:
            parsed_steps = [(f"Step {idx + 1}", bullet) for idx, bullet in enumerate(fallback_bullets[:5])]
        if not parsed_steps:
            parsed_steps = [("Step 1", "No process steps provided.")]

        y = y_top - 10.0
        box_height = 62.0
        for idx, (title, detail) in enumerate(parsed_steps, start=1):
            if y - box_height < y_bottom:
                break
            self._set_pdf_fill_color(pdf, self._style.section_chip_color)
            self._set_pdf_stroke_color(pdf, self._style.section_chip_color)
            pdf.roundRect(40.0, y - box_height, 880.0, box_height, 8.0, fill=1, stroke=0)
            self._set_pdf_fill_color(pdf, self._style.section_chip_text_color)
            pdf.setFont("Helvetica-Bold", 13)
            pdf.drawString(54.0, y - 22.0, f"{idx}. {title}")
            if detail:
                pdf.setFont("Helvetica", 11)
                wrapped = self._wrap_pdf_text(
                    pdf=pdf,
                    text=detail,
                    font_name="Helvetica",
                    font_size=11,
                    max_width=852.0,
                    max_lines=2,
                )
                current_y = y - 38.0
                for line in wrapped:
                    pdf.drawString(54.0, current_y, line)
                    current_y -= 13.0
            y -= box_height + 10.0

    def _draw_pdf_metric_cards(
        self,
        *,
        pdf: Any,
        cards: Any,
        fallback_bullets: list[str],
        y_top: float,
    ) -> None:
        parsed_cards: list[tuple[str, str, str]] = []
        if isinstance(cards, list):
            for card in cards[:4]:
                if not isinstance(card, dict):
                    continue
                label = normalize_text(card.get("label", ""))
                value = normalize_text(card.get("value", ""))
                context = normalize_text(card.get("context", ""))
                if label or value or context:
                    parsed_cards.append((label, value, context))
        if not parsed_cards:
            parsed_cards = [(f"Metric {idx + 1}", bullet, "") for idx, bullet in enumerate(fallback_bullets[:4])]
        if not parsed_cards:
            parsed_cards = [("Metric", "No metric cards provided.", "")]

        positions = [
            (40.0, y_top - 174.0),
            (500.0, y_top - 174.0),
            (40.0, y_top - 366.0),
            (500.0, y_top - 366.0),
        ]
        for idx, (label, value, context) in enumerate(parsed_cards[:4]):
            x, y = positions[idx]
            self._set_pdf_fill_color(pdf, self._style.section_chip_color)
            self._set_pdf_stroke_color(pdf, self._style.section_chip_color)
            pdf.roundRect(x, y, 420.0, 160.0, 10.0, fill=1, stroke=0)
            self._set_pdf_fill_color(pdf, self._style.section_chip_text_color)
            pdf.setFont("Helvetica-Bold", 12)
            pdf.drawString(x + 12.0, y + 138.0, label or "Metric")
            pdf.setFont("Helvetica-Bold", 20)
            value_wrapped = self._wrap_pdf_text(
                pdf=pdf,
                text=value or "-",
                font_name="Helvetica-Bold",
                font_size=20,
                max_width=396.0,
                max_lines=2,
            )
            current_y = y + 108.0
            for line in value_wrapped:
                pdf.drawString(x + 12.0, current_y, line)
                current_y -= 24.0
            if context:
                pdf.setFont("Helvetica", 10)
                pdf.drawString(x + 12.0, y + 18.0, context[:72])

    @staticmethod
    def _to_string_list(value: Any) -> list[str]:
        if not isinstance(value, list):
            return []
        return [normalize_text(item) for item in value if normalize_text(item)]

    def _draw_pdf_background(
        self,
        *,
        pdf: Any,
        page_width: float,
        page_height: float,
    ) -> None:
        self._set_pdf_fill_color(pdf, self._style.background_color)
        self._set_pdf_stroke_color(pdf, self._style.background_color)
        pdf.rect(0.0, 0.0, page_width, page_height, fill=1, stroke=0)
        self._set_pdf_fill_color(pdf, self._style.accent_color)
        self._set_pdf_stroke_color(pdf, self._style.accent_color)
        pdf.rect(0.0, page_height - 10.0, page_width, 10.0, fill=1, stroke=0)

    def _draw_pdf_bullets(
        self,
        *,
        pdf: Any,
        bullets: list[str],
        x: float,
        y_top: float,
        width: float,
        y_bottom: float,
        font_size: int,
    ) -> None:
        y = y_top
        line_height = font_size + 5
        bullet_indent = 18.0
        self._set_pdf_fill_color(pdf, self._style.body_color)
        pdf.setFont("Helvetica", font_size)

        for bullet in bullets:
            wrapped = self._wrap_pdf_text(
                pdf=pdf,
                text=bullet,
                font_name="Helvetica",
                font_size=font_size,
                max_width=width - bullet_indent,
                max_lines=4,
            )
            if not wrapped:
                continue
            needed_height = len(wrapped) * line_height + 7.0
            if y - needed_height < y_bottom:
                break
            pdf.drawString(x, y, "•")
            pdf.drawString(x + bullet_indent, y, wrapped[0])
            y -= line_height
            for continuation in wrapped[1:]:
                pdf.drawString(x + bullet_indent, y, continuation)
                y -= line_height
            y -= 7.0

    def _draw_pdf_code_panel(
        self,
        *,
        pdf: Any,
        code_snippet: str,
        code_language: str,
        x: float,
        y_top: float,
        width: float,
        height: float,
    ) -> None:
        y = y_top - height
        self._set_pdf_fill_color(pdf, self._style.code_panel_color)
        self._set_pdf_stroke_color(pdf, self._style.code_panel_color)
        pdf.roundRect(x, y, width, height, 10.0, fill=1, stroke=0)

        inner_x = x + 14.0
        header_y = y_top - 22.0
        self._set_pdf_fill_color(pdf, self._style.code_text_color)
        pdf.setFont("Helvetica-Bold", 12)
        pdf.drawString(inner_x, header_y, f"Code ({code_language.lower()})")

        code_lines = trim_code_for_slide(code_snippet)
        code_font_size = 10
        pdf.setFont("Courier", code_font_size)
        char_width = max(pdf.stringWidth("M", "Courier", code_font_size), 5.0)
        max_chars = max(18, int((width - 28.0) / char_width))
        max_lines = max(6, int((height - 44.0) / (code_font_size + 2)))
        fitted_lines: list[str] = []
        for line in code_lines:
            for split_line in split_line_for_slide(line=line, max_chars=max_chars):
                if len(fitted_lines) >= max_lines:
                    break
                fitted_lines.append(split_line)
            if len(fitted_lines) >= max_lines:
                break
        if len(fitted_lines) == max_lines and fitted_lines:
            fitted_lines[-1] = (
                fitted_lines[-1][: max_chars - 3] + "..."
                if len(fitted_lines[-1]) > max_chars - 3
                else fitted_lines[-1] + "..."
            )

        current_y = header_y - 16.0
        for line in fitted_lines:
            if current_y < y + 12.0:
                break
            pdf.drawString(inner_x, current_y, line)
            current_y -= code_font_size + 2.0

    def _wrap_pdf_text(
        self,
        *,
        pdf: Any,
        text: str,
        font_name: str,
        font_size: int,
        max_width: float,
        max_lines: int | None,
    ) -> list[str]:
        words = str(text).split()
        if not words:
            return []

        lines: list[str] = []
        current = words[0]
        for word in words[1:]:
            candidate = f"{current} {word}"
            if pdf.stringWidth(candidate, font_name, font_size) <= max_width:
                current = candidate
                continue
            lines.append(current)
            current = word
            if max_lines is not None and len(lines) >= max_lines:
                break
        if max_lines is None or len(lines) < max_lines:
            lines.append(current)
        if max_lines is not None and len(lines) > max_lines:
            lines = lines[:max_lines]
        if max_lines is not None and len(lines) == max_lines:
            lines[-1] = self._truncate_pdf_line(
                pdf=pdf,
                text=lines[-1],
                font_name=font_name,
                font_size=font_size,
                max_width=max_width,
            )
        return lines

    @staticmethod
    def _truncate_pdf_line(
        *,
        pdf: Any,
        text: str,
        font_name: str,
        font_size: int,
        max_width: float,
    ) -> str:
        candidate = text
        suffix = "..."
        while candidate and pdf.stringWidth(candidate + suffix, font_name, font_size) > max_width:
            candidate = candidate[:-1]
        return (candidate + suffix) if candidate else suffix
