from __future__ import annotations

from io import BytesIO
from typing import Any

from main_app.shared.slideshow.representation_normalizer import normalize_slide_representation
from main_app.services.pptx_export.models import PptxTemplateStyle
from main_app.services.pptx_export.text_utils import normalize_text, prepare_code_payload, trim_code_for_slide


class PptxDeckBuilder:
    def __init__(self, *, style: PptxTemplateStyle) -> None:
        self._style = style

    def build(self, *, topic: str, slides: list[dict[str, Any]]) -> tuple[bytes | None, str | None]:
        try:
            from pptx import Presentation  # type: ignore
            from pptx.dml.color import RGBColor  # type: ignore
            from pptx.enum.shapes import MSO_SHAPE  # type: ignore
            from pptx.util import Inches, Pt  # type: ignore
        except Exception:
            return None, "python-pptx is not installed. Install dependencies to enable PPTX export."

        prs = Presentation()
        blank_layout = prs.slide_layouts[6] if len(prs.slide_layouts) > 6 else prs.slide_layouts[0]

        self._add_title_slide(
            prs=prs,
            blank_layout=blank_layout,
            topic=topic,
            Inches=Inches,
            Pt=Pt,
            RGBColor=RGBColor,
            MSO_SHAPE=MSO_SHAPE,
        )

        for item in slides:
            self._add_content_slide(
                prs=prs,
                blank_layout=blank_layout,
                item=item,
                Inches=Inches,
                Pt=Pt,
                RGBColor=RGBColor,
                MSO_SHAPE=MSO_SHAPE,
            )

        output = BytesIO()
        prs.save(output)
        return output.getvalue(), None

    @staticmethod
    def _rgb(rgb_cls: Any, color: tuple[int, int, int]) -> Any:
        return rgb_cls(int(color[0]), int(color[1]), int(color[2]))

    def _add_title_slide(
        self,
        *,
        prs: Any,
        blank_layout: Any,
        topic: str,
        Inches: Any,
        Pt: Any,
        RGBColor: Any,
        MSO_SHAPE: Any,
    ) -> None:
        slide = prs.slides.add_slide(blank_layout)
        self._set_slide_background(slide=slide, RGBColor=RGBColor)
        self._add_accent_bar(
            slide=slide,
            width=prs.slide_width,
            Inches=Inches,
            RGBColor=RGBColor,
            MSO_SHAPE=MSO_SHAPE,
        )

        title_shape = slide.shapes.add_textbox(Inches(0.8), Inches(1.4), Inches(11.8), Inches(1.8))
        title_frame = title_shape.text_frame
        title_frame.clear()
        title_paragraph = title_frame.paragraphs[0]
        title_paragraph.text = normalize_text(topic) or "Slide Deck"
        title_font = title_paragraph.font
        title_font.bold = True
        title_font.size = Pt(48)
        title_font.name = self._style.font_name
        title_font.color.rgb = self._rgb(RGBColor, self._style.title_color)

        subtitle_shape = slide.shapes.add_textbox(Inches(0.8), Inches(3.5), Inches(11.8), Inches(1.0))
        subtitle_frame = subtitle_shape.text_frame
        subtitle_frame.clear()
        subtitle_paragraph = subtitle_frame.paragraphs[0]
        subtitle_paragraph.text = f"Generated by Knowledge App | Template: {self._style.title}"
        subtitle_font = subtitle_paragraph.font
        subtitle_font.size = Pt(20)
        subtitle_font.name = self._style.font_name
        subtitle_font.color.rgb = self._rgb(RGBColor, self._style.body_color)

    def _add_content_slide(
        self,
        *,
        prs: Any,
        blank_layout: Any,
        item: dict[str, Any],
        Inches: Any,
        Pt: Any,
        RGBColor: Any,
        MSO_SHAPE: Any,
    ) -> None:
        normalized_item, _ = normalize_slide_representation(item if isinstance(item, dict) else {})
        slide = prs.slides.add_slide(blank_layout)
        self._set_slide_background(slide=slide, RGBColor=RGBColor)
        self._add_accent_bar(
            slide=slide,
            width=prs.slide_width,
            Inches=Inches,
            RGBColor=RGBColor,
            MSO_SHAPE=MSO_SHAPE,
        )

        section = normalize_text(normalized_item.get("section", ""))
        if section:
            self._add_section_chip(
                slide=slide,
                section=section,
                Inches=Inches,
                Pt=Pt,
                RGBColor=RGBColor,
                MSO_SHAPE=MSO_SHAPE,
            )

        title = normalize_text(normalized_item.get("title", "Untitled")) or "Untitled"
        title_shape = slide.shapes.add_textbox(Inches(0.7), Inches(0.7), Inches(11.9), Inches(1.0))
        title_frame = title_shape.text_frame
        title_frame.clear()
        title_paragraph = title_frame.paragraphs[0]
        title_paragraph.text = title
        title_font = title_paragraph.font
        title_font.bold = True
        title_font.size = Pt(34)
        title_font.name = self._style.font_name
        title_font.color.rgb = self._rgb(RGBColor, self._style.title_color)

        raw_code_snippet = str(normalized_item.get("code_snippet", ""))
        raw_code_language = normalize_text(normalized_item.get("code_language", ""))
        code_snippet, code_language = prepare_code_payload(
            code_snippet=raw_code_snippet,
            code_language=raw_code_language,
        )
        bullets = normalized_item.get("bullets", [])
        if not isinstance(bullets, list):
            bullets = []
        bullet_texts = [normalize_text(bullet) for bullet in bullets if normalize_text(bullet)]
        if not bullet_texts:
            bullet_texts = ["Key concept summary for this slide."]
        representation = " ".join(str(normalized_item.get("representation", "bullet")).split()).strip().lower()
        layout_payload = normalized_item.get("layout_payload", {})
        if not isinstance(layout_payload, dict):
            layout_payload = {}

        if code_snippet:
            bullet_box = slide.shapes.add_textbox(Inches(0.7), Inches(1.9), Inches(5.9), Inches(4.9))
            self._write_bullets(
                text_frame=bullet_box.text_frame,
                bullets=bullet_texts,
                font_size=22,
                Pt=Pt,
                RGBColor=RGBColor,
            )
            self._add_code_panel(
                slide=slide,
                code_snippet=code_snippet,
                code_language=code_language,
                Inches=Inches,
                Pt=Pt,
                RGBColor=RGBColor,
                MSO_SHAPE=MSO_SHAPE,
            )
        else:
            self._render_representation_body(
                slide=slide,
                representation=representation,
                layout_payload=layout_payload,
                bullet_texts=bullet_texts,
                Inches=Inches,
                Pt=Pt,
                RGBColor=RGBColor,
                MSO_SHAPE=MSO_SHAPE,
            )

        notes = str(normalized_item.get("speaker_notes", "")).strip()
        if notes:
            notes_frame = slide.notes_slide.notes_text_frame
            notes_frame.clear()
            notes_frame.text = notes

    def _render_representation_body(
        self,
        *,
        slide: Any,
        representation: str,
        layout_payload: dict[str, Any],
        bullet_texts: list[str],
        Inches: Any,
        Pt: Any,
        RGBColor: Any,
        MSO_SHAPE: Any,
    ) -> None:
        if representation == "two_column":
            self._render_two_column_body(
                slide=slide,
                left_title=str(layout_payload.get("left_title", "Left")),
                left_items=self._as_string_list(layout_payload.get("left_items")),
                right_title=str(layout_payload.get("right_title", "Right")),
                right_items=self._as_string_list(layout_payload.get("right_items")),
                fallback_bullets=bullet_texts,
                Inches=Inches,
                Pt=Pt,
                RGBColor=RGBColor,
            )
            return
        if representation == "timeline":
            self._render_timeline_body(
                slide=slide,
                events=layout_payload.get("events"),
                fallback_bullets=bullet_texts,
                Inches=Inches,
                Pt=Pt,
                RGBColor=RGBColor,
                MSO_SHAPE=MSO_SHAPE,
            )
            return
        if representation == "comparison":
            self._render_two_column_body(
                slide=slide,
                left_title=str(layout_payload.get("left_title", "Option A")),
                left_items=self._as_string_list(layout_payload.get("left_points")),
                right_title=str(layout_payload.get("right_title", "Option B")),
                right_items=self._as_string_list(layout_payload.get("right_points")),
                fallback_bullets=bullet_texts,
                Inches=Inches,
                Pt=Pt,
                RGBColor=RGBColor,
            )
            return
        if representation == "process_flow":
            self._render_process_flow_body(
                slide=slide,
                steps=layout_payload.get("steps"),
                fallback_bullets=bullet_texts,
                Inches=Inches,
                Pt=Pt,
                RGBColor=RGBColor,
                MSO_SHAPE=MSO_SHAPE,
            )
            return
        if representation == "metric_cards":
            self._render_metric_cards_body(
                slide=slide,
                cards=layout_payload.get("cards"),
                fallback_bullets=bullet_texts,
                Inches=Inches,
                Pt=Pt,
                RGBColor=RGBColor,
                MSO_SHAPE=MSO_SHAPE,
            )
            return
        bullet_box = slide.shapes.add_textbox(Inches(0.8), Inches(1.9), Inches(11.4), Inches(4.9))
        self._write_bullets(
            text_frame=bullet_box.text_frame,
            bullets=bullet_texts,
            font_size=24,
            Pt=Pt,
            RGBColor=RGBColor,
        )

    def _set_slide_background(self, *, slide: Any, RGBColor: Any) -> None:
        fill = slide.background.fill
        fill.solid()
        fill.fore_color.rgb = self._rgb(RGBColor, self._style.background_color)

    def _add_accent_bar(
        self,
        *,
        slide: Any,
        width: int,
        Inches: Any,
        RGBColor: Any,
        MSO_SHAPE: Any,
    ) -> None:
        bar = slide.shapes.add_shape(MSO_SHAPE.RECTANGLE, 0, 0, width, Inches(0.22))
        bar.fill.solid()
        bar.fill.fore_color.rgb = self._rgb(RGBColor, self._style.accent_color)
        bar.line.fill.background()

    def _add_section_chip(
        self,
        *,
        slide: Any,
        section: str,
        Inches: Any,
        Pt: Any,
        RGBColor: Any,
        MSO_SHAPE: Any,
    ) -> None:
        chip = slide.shapes.add_shape(MSO_SHAPE.ROUNDED_RECTANGLE, Inches(9.4), Inches(0.55), Inches(3.0), Inches(0.45))
        chip.fill.solid()
        chip.fill.fore_color.rgb = self._rgb(RGBColor, self._style.section_chip_color)
        chip.line.fill.background()

        chip_frame = chip.text_frame
        chip_frame.clear()
        chip_paragraph = chip_frame.paragraphs[0]
        chip_paragraph.text = section[:36]
        chip_font = chip_paragraph.font
        chip_font.bold = True
        chip_font.size = Pt(13)
        chip_font.name = self._style.font_name
        chip_font.color.rgb = self._rgb(RGBColor, self._style.section_chip_text_color)

    def _write_bullets(
        self,
        *,
        text_frame: Any,
        bullets: list[str],
        font_size: int,
        Pt: Any,
        RGBColor: Any,
    ) -> None:
        text_frame.clear()
        limited_bullets = bullets[:6]
        for idx, bullet in enumerate(limited_bullets):
            paragraph = text_frame.paragraphs[0] if idx == 0 else text_frame.add_paragraph()
            paragraph.text = f"- {bullet}"
            paragraph.level = 0
            paragraph.space_after = Pt(10)
            paragraph.line_spacing = 1.2
            paragraph_font = paragraph.font
            paragraph_font.size = Pt(font_size)
            paragraph_font.name = self._style.font_name
            paragraph_font.color.rgb = self._rgb(RGBColor, self._style.body_color)

    def _render_two_column_body(
        self,
        *,
        slide: Any,
        left_title: str,
        left_items: list[str],
        right_title: str,
        right_items: list[str],
        fallback_bullets: list[str],
        Inches: Any,
        Pt: Any,
        RGBColor: Any,
    ) -> None:
        if not left_items and not right_items:
            midpoint = max(1, len(fallback_bullets) // 2)
            left_items = fallback_bullets[:midpoint]
            right_items = fallback_bullets[midpoint:]

        left_heading = slide.shapes.add_textbox(Inches(0.8), Inches(1.86), Inches(5.4), Inches(0.45))
        left_heading_frame = left_heading.text_frame
        left_heading_frame.clear()
        left_title_paragraph = left_heading_frame.paragraphs[0]
        left_title_paragraph.text = normalize_text(left_title) or "Left"
        left_title_font = left_title_paragraph.font
        left_title_font.bold = True
        left_title_font.size = Pt(20)
        left_title_font.name = self._style.font_name
        left_title_font.color.rgb = self._rgb(RGBColor, self._style.title_color)

        right_heading = slide.shapes.add_textbox(Inches(6.2), Inches(1.86), Inches(5.4), Inches(0.45))
        right_heading_frame = right_heading.text_frame
        right_heading_frame.clear()
        right_title_paragraph = right_heading_frame.paragraphs[0]
        right_title_paragraph.text = normalize_text(right_title) or "Right"
        right_title_font = right_title_paragraph.font
        right_title_font.bold = True
        right_title_font.size = Pt(20)
        right_title_font.name = self._style.font_name
        right_title_font.color.rgb = self._rgb(RGBColor, self._style.title_color)

        left_box = slide.shapes.add_textbox(Inches(0.8), Inches(2.28), Inches(5.2), Inches(4.6))
        self._write_bullets(
            text_frame=left_box.text_frame,
            bullets=left_items[:4] or ["No content provided."],
            font_size=20,
            Pt=Pt,
            RGBColor=RGBColor,
        )
        right_box = slide.shapes.add_textbox(Inches(6.2), Inches(2.28), Inches(5.2), Inches(4.6))
        self._write_bullets(
            text_frame=right_box.text_frame,
            bullets=right_items[:4] or ["No content provided."],
            font_size=20,
            Pt=Pt,
            RGBColor=RGBColor,
        )

    def _render_timeline_body(
        self,
        *,
        slide: Any,
        events: Any,
        fallback_bullets: list[str],
        Inches: Any,
        Pt: Any,
        RGBColor: Any,
        MSO_SHAPE: Any,
    ) -> None:
        parsed_events: list[dict[str, str]] = []
        if isinstance(events, list):
            for item in events[:5]:
                if not isinstance(item, dict):
                    continue
                label = normalize_text(item.get("label", ""))
                detail = normalize_text(item.get("detail", ""))
                if not label and not detail:
                    continue
                parsed_events.append({"label": label, "detail": detail})
        if not parsed_events:
            parsed_events = [{"label": f"Milestone {idx + 1}", "detail": text} for idx, text in enumerate(fallback_bullets[:5])]
        if not parsed_events:
            parsed_events = [{"label": "Milestone", "detail": "No timeline events provided."}]

        start_y = 2.05
        step = 0.95
        for idx, event in enumerate(parsed_events):
            y = start_y + idx * step
            marker = slide.shapes.add_shape(MSO_SHAPE.OVAL, Inches(0.95), Inches(y + 0.11), Inches(0.2), Inches(0.2))
            marker.fill.solid()
            marker.fill.fore_color.rgb = self._rgb(RGBColor, self._style.accent_color)
            marker.line.fill.background()

            line = slide.shapes.add_shape(MSO_SHAPE.RECTANGLE, Inches(1.05), Inches(y + 0.2), Inches(0.05), Inches(0.7))
            line.fill.solid()
            line.fill.fore_color.rgb = self._rgb(RGBColor, self._style.accent_color)
            line.line.fill.background()

            event_box = slide.shapes.add_textbox(Inches(1.3), Inches(y), Inches(10.8), Inches(0.88))
            frame = event_box.text_frame
            frame.clear()
            header = frame.paragraphs[0]
            header.text = event.get("label") or f"Milestone {idx + 1}"
            header_font = header.font
            header_font.bold = True
            header_font.size = Pt(18)
            header_font.name = self._style.font_name
            header_font.color.rgb = self._rgb(RGBColor, self._style.title_color)
            detail_text = event.get("detail", "")
            if detail_text:
                detail_paragraph = frame.add_paragraph()
                detail_paragraph.text = detail_text
                detail_paragraph.level = 0
                detail_paragraph.space_after = Pt(0)
                detail_font = detail_paragraph.font
                detail_font.size = Pt(16)
                detail_font.name = self._style.font_name
                detail_font.color.rgb = self._rgb(RGBColor, self._style.body_color)

    def _render_process_flow_body(
        self,
        *,
        slide: Any,
        steps: Any,
        fallback_bullets: list[str],
        Inches: Any,
        Pt: Any,
        RGBColor: Any,
        MSO_SHAPE: Any,
    ) -> None:
        parsed_steps: list[dict[str, str]] = []
        if isinstance(steps, list):
            for item in steps[:5]:
                if not isinstance(item, dict):
                    continue
                title = normalize_text(item.get("title", ""))
                detail = normalize_text(item.get("detail", ""))
                if not title and not detail:
                    continue
                parsed_steps.append({"title": title or "Step", "detail": detail})
        if not parsed_steps:
            parsed_steps = [{"title": f"Step {idx + 1}", "detail": text} for idx, text in enumerate(fallback_bullets[:5])]
        if not parsed_steps:
            parsed_steps = [{"title": "Step 1", "detail": "No process steps provided."}]

        start_y = 1.95
        height = 0.9
        for idx, step in enumerate(parsed_steps):
            y = start_y + idx * 1.0
            box = slide.shapes.add_shape(MSO_SHAPE.ROUNDED_RECTANGLE, Inches(0.9), Inches(y), Inches(10.9), Inches(height))
            box.fill.solid()
            box.fill.fore_color.rgb = self._rgb(RGBColor, self._style.section_chip_color)
            box.line.fill.background()
            frame = box.text_frame
            frame.clear()
            title_paragraph = frame.paragraphs[0]
            title_paragraph.text = f"{idx + 1}. {step.get('title', f'Step {idx + 1}')}"
            title_font = title_paragraph.font
            title_font.bold = True
            title_font.size = Pt(16)
            title_font.name = self._style.font_name
            title_font.color.rgb = self._rgb(RGBColor, self._style.section_chip_text_color)
            detail = step.get("detail", "")
            if detail:
                detail_paragraph = frame.add_paragraph()
                detail_paragraph.text = detail
                detail_paragraph.level = 0
                detail_font = detail_paragraph.font
                detail_font.size = Pt(13)
                detail_font.name = self._style.font_name
                detail_font.color.rgb = self._rgb(RGBColor, self._style.section_chip_text_color)

    def _render_metric_cards_body(
        self,
        *,
        slide: Any,
        cards: Any,
        fallback_bullets: list[str],
        Inches: Any,
        Pt: Any,
        RGBColor: Any,
        MSO_SHAPE: Any,
    ) -> None:
        parsed_cards: list[dict[str, str]] = []
        if isinstance(cards, list):
            for card in cards[:4]:
                if not isinstance(card, dict):
                    continue
                label = normalize_text(card.get("label", ""))
                value = normalize_text(card.get("value", ""))
                context = normalize_text(card.get("context", ""))
                if not label and not value and not context:
                    continue
                parsed_cards.append({"label": label, "value": value, "context": context})
        if not parsed_cards:
            for idx, bullet in enumerate(fallback_bullets[:4], start=1):
                parsed_cards.append({"label": f"Metric {idx}", "value": bullet, "context": ""})
        if not parsed_cards:
            parsed_cards = [{"label": "Metric", "value": "No metric cards provided.", "context": ""}]

        positions = [
            (0.8, 2.0),
            (6.3, 2.0),
            (0.8, 4.25),
            (6.3, 4.25),
        ]
        for idx, card in enumerate(parsed_cards[:4]):
            x, y = positions[idx]
            box = slide.shapes.add_shape(MSO_SHAPE.ROUNDED_RECTANGLE, Inches(x), Inches(y), Inches(5.0), Inches(2.0))
            box.fill.solid()
            box.fill.fore_color.rgb = self._rgb(RGBColor, self._style.section_chip_color)
            box.line.fill.background()
            frame = box.text_frame
            frame.clear()
            label_paragraph = frame.paragraphs[0]
            label_paragraph.text = card.get("label", "Metric")
            label_font = label_paragraph.font
            label_font.size = Pt(13)
            label_font.bold = True
            label_font.name = self._style.font_name
            label_font.color.rgb = self._rgb(RGBColor, self._style.section_chip_text_color)
            value_paragraph = frame.add_paragraph()
            value_paragraph.text = card.get("value", "")
            value_font = value_paragraph.font
            value_font.size = Pt(19)
            value_font.bold = True
            value_font.name = self._style.font_name
            value_font.color.rgb = self._rgb(RGBColor, self._style.section_chip_text_color)
            context = card.get("context", "")
            if context:
                context_paragraph = frame.add_paragraph()
                context_paragraph.text = context
                context_font = context_paragraph.font
                context_font.size = Pt(11)
                context_font.name = self._style.font_name
                context_font.color.rgb = self._rgb(RGBColor, self._style.section_chip_text_color)

    @staticmethod
    def _as_string_list(value: Any) -> list[str]:
        if not isinstance(value, list):
            return []
        return [normalize_text(item) for item in value if normalize_text(item)]

    def _add_code_panel(
        self,
        *,
        slide: Any,
        code_snippet: str,
        code_language: str,
        Inches: Any,
        Pt: Any,
        RGBColor: Any,
        MSO_SHAPE: Any,
    ) -> None:
        panel_left = Inches(6.75)
        panel_top = Inches(1.72)
        panel_width = Inches(5.72)
        panel_height = Inches(5.25)

        panel = slide.shapes.add_shape(
            MSO_SHAPE.ROUNDED_RECTANGLE,
            panel_left,
            panel_top,
            panel_width,
            panel_height,
        )
        panel.fill.solid()
        panel.fill.fore_color.rgb = self._rgb(RGBColor, self._style.code_panel_color)
        panel.line.fill.background()

        code_lines = trim_code_for_slide(code_snippet)
        max_line_length = max((len(line) for line in code_lines), default=0)
        code_font_size = 13 if len(code_lines) <= 12 and max_line_length <= 74 else 12 if len(code_lines) <= 17 else 11

        header_shape = slide.shapes.add_textbox(
            panel_left + Inches(0.2),
            panel_top + Inches(0.12),
            panel_width - Inches(0.35),
            Inches(0.32),
        )
        header_frame = header_shape.text_frame
        header_frame.clear()
        header_frame.word_wrap = False
        header = header_frame.paragraphs[0]
        header.text = f"Code ({code_language.lower()})"
        header_font = header.font
        header_font.bold = True
        header_font.size = Pt(14)
        header_font.name = self._style.font_name
        header_font.color.rgb = self._rgb(RGBColor, self._style.code_text_color)

        code_shape = slide.shapes.add_textbox(
            panel_left + Inches(0.2),
            panel_top + Inches(0.55),
            panel_width - Inches(0.35),
            panel_height - Inches(0.74),
        )
        code_frame = code_shape.text_frame
        code_frame.clear()
        code_frame.word_wrap = False
        code_frame.margin_left = 0
        code_frame.margin_right = 0
        code_frame.margin_top = 0
        code_frame.margin_bottom = 0

        for idx, line in enumerate(code_lines):
            paragraph = code_frame.paragraphs[0] if idx == 0 else code_frame.add_paragraph()
            paragraph.text = line
            paragraph.level = 0
            paragraph.space_after = Pt(0)
            paragraph.line_spacing = 1.0
            code_font = paragraph.font
            code_font.name = "Consolas"
            code_font.size = Pt(code_font_size)
            code_font.color.rgb = self._rgb(RGBColor, self._style.code_text_color)
