from __future__ import annotations


E_TOOL_NOT_REGISTERED = "E_TOOL_NOT_REGISTERED"
E_PAYLOAD_MISSING_MANDATORY = "E_PAYLOAD_MISSING_MANDATORY"
E_DEPENDENCY_MISSING = "E_DEPENDENCY_MISSING"
E_EXECUTOR_FAILED = "E_EXECUTOR_FAILED"
E_ARTIFACT_NORMALIZATION_FAILED = "E_ARTIFACT_NORMALIZATION_FAILED"
E_VERIFY_FAILED = "E_VERIFY_FAILED"
E_WORKFLOW_CYCLE = "E_WORKFLOW_CYCLE"
E_PARSE_FAILED = "E_PARSE_FAILED"
E_STAGE_TIMEOUT = "E_STAGE_TIMEOUT"
E_STAGE_EXCEPTION = "E_STAGE_EXCEPTION"
E_VERIFY_PROFILE_UNKNOWN = "E_VERIFY_PROFILE_UNKNOWN"
E_ARTIFACT_SCHEMA_MISMATCH = "E_ARTIFACT_SCHEMA_MISMATCH"
E_POLICY_GATE_FAILED = "E_POLICY_GATE_FAILED"
E_POLICY_PROFILE_UNKNOWN = "E_POLICY_PROFILE_UNKNOWN"
E_RUN_LEDGER_WRITE_FAILED = "E_RUN_LEDGER_WRITE_FAILED"
E_PARALLEL_SCHEDULER_FAILURE = "E_PARALLEL_SCHEDULER_FAILURE"
E_DEDUP_SIGNATURE_INVALID = "E_DEDUP_SIGNATURE_INVALID"
E_SCHEMA_VALIDATION_FAILED = "E_SCHEMA_VALIDATION_FAILED"
E_PLUGIN_SPEC_INVALID = "E_PLUGIN_SPEC_INVALID"
E_STATE_TRANSITION_INVALID = "E_STATE_TRANSITION_INVALID"
E_PLUGIN_SPEC_HINT_AVAILABLE = "E_PLUGIN_SPEC_HINT_AVAILABLE"
E_SIMULATION_INVALID_PLAN = "E_SIMULATION_INVALID_PLAN"
E_SCAFFOLD_TEMPLATE_MISSING = "E_SCAFFOLD_TEMPLATE_MISSING"


def map_exception_to_error_code(exc: BaseException) -> str:
    if isinstance(exc, TimeoutError):
        return E_STAGE_TIMEOUT
    return E_STAGE_EXCEPTION
